### ISSUE TITLE
AWS replace-vm does not honour Instance Profile

### ISSUE THREAD

**Issue by sturadnidge** [pivotal-cf/cliaas#6]
If you want to configure Ops Manager to use instance profiles rather an access key + secret key, you need to assign an IAM Role to the Ops Manager VM at creation time, so that it can pass the specified role to the BOSH machine it creates.

cliaas doesn't seem to apply the same IAM Role to a new Ops Manager instance created by `replace-vm`, resulting in broken pcf-pipelines (for example).

**Comment by sturadnidge** [comment]
From what I can tell, `ec2Client.DescribeInstances` will return an `IamInstanceProfile` attribute, which could be grabbed by `GetVMInfo` and passed through to CreateVM for use in `ec2.RunInstances`? Unfortunately it's not a string... I could probably take a shot at a PR, but I'm pretty new to Go so it might be ugly!

**Comment by abbyachau** [comment]
Closing this issue as it's been delivered some time ago.
