### ISSUE TITLE
GCP - Replace VM

### ISSUE THREAD

**Issue by fmarinelli** [pivotal-cf/cliaas#8]
When launching cliaas with command replace-vm, it doesn't seem to use the disk size parameter and I end up with a new VM with only 5GB disk

To reproduce:
cliaas-linux replace-vm \
  --config cliaas-config/config.yml \
  --identifier "identifier" \
  --disk-size-gb "150"

---> cliaas-config/config.yml
gcp:
  credfile: cliaas-config/gcpcreds.json
  zone: europe-west1-c
  project: fe-fmarinelli
  disk_image_url: ops-manager-eu/pcf-gcp-2.0-build.255.tar.gz

**Comment by abbyachau** [comment]
@fmarinelli thanks for creating this issue. Are you using the upgrade-ops-manager pipeline for GCP, if so what version of the pipelines are you using? and where have you obtained it (via PivNet or GitHub (if GitHub, are you using a tag). Thanks.

**Comment by fmarinelli** [comment]
Hello, I'm using the master branch from github.

I've also tried the command directly from the shell.

**Comment by abbyachau** [comment]
Hi @fmarinelli the master branch is considered unstable since our engineers iterate on that branch. Could you download v23 from PivNet or use a tag on Github and try your pipeline again. Thank you.

**Comment by abbyachau** [comment]
Hey again @fmarinelli we are working on a fix for the issue you've described. We hope to release the fix soon. Thanks for reporting the issue.

**Comment by abbyachau** [comment]
Hi @fmarinelli we've pushed out a fix for this issue - see release notes for `v23.1` and the Upgrade Pipelines [section](https://github.com/pivotal-cf/pcf-pipelines/releases) for more information. Please do not hesitate to reach out should you have any feedback/further comments.
